export const randomPhotos = {
  GET_RANDOM_PHOTOS_REQUEST: '@randomPhotos/GET_RANDOM_PHOTOS_REQUEST',
  GET_RANDOM_PHOTOS_SUCCESS: '@randomPhotos/GET_RANDOM_PHOTOS_SUCCESS',
  GET_RANDOM_PHOTOS_FAILURE: '@randomPhotos/GET_RANDOM_PHOTOS_FAILURE',
}