export const randomPhotos = {
  RANDOM_PHOTOS_GET_REQUEST: '@randomPhotos/RANDOM_PHOTOS_GET_REQUEST',
  RANDOM_PHOTOS_GET_COMMIT: '@randomPhotos/RANDOM_PHOTOS_GET_COMMIT',
  RANDOM_PHOTOS_GET_ROLLBACK: '@randomPhotos/RANDOM_PHOTOS_GET_ROLLBACK',
}